import { clock, phase, presets, type Settings } from '../core/settings';
const arrow='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
const sun='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="12" cy="12" r="4"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/></svg>';
const gear='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="m10 3-.6 2-2 .9-2-.5-2 3 1.5 1.6v3L3 15l2 3 2-.5 2 .9.6 2.1h4l.6-2.1 2-.9 2 .5 2-3-1.5-2v-3L21 8.4l-2-3-2 .5-2-.9-.6-2.1z"/><circle cx="12" cy="12" r="3"/></svg>';
const palm='<svg viewBox="0 0 32 40" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M13 38c6-8 6-16 4-24M17 14C8 9 3 13 1 20c7-5 10-5 16-6Zm0 0c4-9 9-10 14-5-7 0-10 2-14 5Zm0 0C13 4 7 4 4 8c6 0 8 2 13 6Zm0 0c8-2 12 3 12 10-4-5-7-8-12-10Zm0 0c0-7 2-11 6-12"/></svg>';
export interface UIActions {play:()=>void;pause:()=>void;home:()=>void;settings:(patch:Partial<Settings>)=>void;view:(view:number)=>void;respawn:()=>void;reset:()=>void}
export class UI {
  root:HTMLElement;menu:HTMLElement;hud:HTMLElement;dialog:HTMLDialogElement;loading:HTMLElement;toast:HTMLElement;private toastTimer=0;
  constructor(private settings:Settings,private actions:UIActions) {
    document.querySelector('#app')!.innerHTML=`<main id="game-shell"><div id="scene"></div>
    <div id="loading" role="status"><div class="loading-mark">${palm}</div><span class="eyebrow">COASTAL CITY</span><h2>Your escape is taking shape.</h2><div class="loading-track"><i id="loading-bar"></i></div><p id="loading-label">Preparing the coastline</p></div>
    <div id="menu" class="menu"><header class="topbar"><a class="brand" href="#" aria-label="Coastal City home">${palm}<span>COASTAL<br/>CITY<span class="brand-dot">®</span></span></a><div class="top-center"><i class="status-dot"></i>A WORLD OF YOUR OWN</div><button class="icon-button" id="open-settings" aria-label="Open settings">${gear}</button></header>
    <section class="hero"><div class="eyebrow hero-kicker"><span class="little-line"></span> YOUR NEXT CHAPTER STARTS HERE</div><h1>Less ordinary.<br/>More <em>coastal.</em></h1><p class="hero-description">An open road. An endless horizon.<br/>A little world that&apos;s yours to explore.</p><div class="hero-actions"><button class="primary-button" id="play"><span>Enter the city</span>${arrow}</button><button class="text-button" id="how-to-play">How to play <span>↗</span></button></div><div class="game-meta"><span><i class="status-dot"></i> FREE TO EXPLORE</span><b>·</b><span>NO DOWNLOAD NEEDED</span></div></section>
    <aside class="location-card"><span class="location-number">01 / 03</span><div class="location-line"></div><div><span class="eyebrow">SOMEWHERE YOU&apos;D RATHER BE</span><h2 id="location-title">The waterfront</h2><span id="location-subtitle">Ocean air. City energy.</span></div><button id="next-view" aria-label="Next scenic viewpoint">${arrow}</button></aside>
    <footer class="menu-footer"><div class="weather-pill">${sun}<span id="menu-weather">27° <b>Clear skies</b></span><span class="footer-divider"></span><span id="menu-time">15:42</span></div><div class="destination-nav" aria-label="Scenic viewpoints"><button data-view="0" class="active" aria-label="View waterfront">01 <span>WATERFRONT</span></button><button data-view="1" aria-label="View downtown">02 <span>DOWNTOWN</span></button><button data-view="2" aria-label="View island">03 <span>ISLAND LIFE</span></button></div><span class="build-label">A SMALL WORLD. A BIG ESCAPE. <span>V 0.1</span></span></footer>
    <div class="scene-credit"><span class="live-dot"></span> LIVE IN-GAME WORLD</div></div>
    <section id="hud" hidden aria-label="Game controls"><header class="hud-top"><div class="hud-brand">${palm}<div>COASTAL CITY<small id="district-name">Marina waterfront</small></div></div><div class="hud-time">${sun}<span id="game-time">15:42</span></div><button class="icon-button" id="pause" aria-label="Pause game">Ⅱ</button></header><div class="discovery"><span class="eyebrow">TAKE THE SCENIC ROUTE</span><p id="objective">Discover the waterfront, marina & island</p><div class="checkpoints"><span id="cp-0">01 Waterfront</span><span id="cp-1">02 Marina</span><span id="cp-2">03 Paloma Island</span></div></div><div class="hud-bottom"><div class="minimap-wrap"><canvas id="minimap" width="280" height="280" aria-label="Local district minimap"></canvas><span>N</span></div><div class="desktop-controls"><span><kbd>W A S D</kbd> Move</span><span><kbd>SHIFT</kbd> Sprint</span><span><kbd>SPACE</kbd> Jump / Brake</span><span><kbd>E</kbd> Interact</span><span>Drag to look</span></div><div id="mode-pill">ON FOOT</div></div><div id="interaction" hidden><kbd>E</kbd><span>Enter vehicle</span></div><div id="touch-controls"><div id="joystick" aria-label="Movement joystick"><span id="joystick-nub"></span></div><div class="touch-actions"><button data-action="ShiftLeft" aria-label="Sprint">RUN</button><button data-action="Space" aria-label="Jump or brake">↑</button><button data-action="KeyE" aria-label="Interact">E</button></div></div></section>
    <aside id="performance" hidden></aside><div id="toast" role="status" hidden></div>
    <dialog id="panel"><div class="panel-header"><div><span class="eyebrow">MAKE YOURSELF AT HOME</span><h2 id="panel-title">Your kind of escape.</h2></div><button id="close-panel" class="icon-button" aria-label="Close menu">×</button></div><nav class="panel-tabs"><button data-tab="graphics" class="active">Graphics</button><button data-tab="world">World</button><button data-tab="controls">Controls</button></nav><div id="panel-body"></div><div class="panel-footer"><button id="resume" class="primary-button">Back to the coast ${arrow}</button><button id="return-home" class="text-button">Main menu</button></div></dialog>
    </main>`;
    this.root=document.querySelector('#game-shell')!;this.menu=document.querySelector('#menu')!;this.hud=document.querySelector('#hud')!;this.dialog=document.querySelector('#panel')!;this.loading=document.querySelector('#loading')!;this.toast=document.querySelector('#toast')!;
    const click=(id:string,fn:()=>void)=>document.getElementById(id)!.addEventListener('click',fn);
    click('play',actions.play);click('open-settings',()=>this.open('graphics'));click('how-to-play',()=>this.open('controls'));click('pause',actions.pause);click('close-panel',()=>this.close());click('resume',()=>this.close());click('return-home',()=>{this.dialog.close();actions.home();});
    let view=0;click('next-view',()=>{view=(view+1)%3;this.setView(view);});document.querySelectorAll<HTMLElement>('[data-view]').forEach(el=>el.onclick=()=>{view=Number(el.dataset.view);this.setView(view);});
    document.querySelectorAll<HTMLElement>('[data-tab]').forEach(el=>el.onclick=()=>this.renderTab(el.dataset.tab!));
    this.dialog.addEventListener('cancel',e=>{e.preventDefault();this.close();});
  }
  progress(p:number,label:string){document.querySelector<HTMLElement>('#loading-bar')!.style.width=`${Math.round(p*100)}%`;document.querySelector('#loading-label')!.textContent=label;}
  ready(){this.loading.classList.add('loaded');setTimeout(()=>this.loading.hidden=true,500);}
  failure(message:string){this.loading.innerHTML=`<h2>This device couldn&apos;t open the city.</h2><p id="failure-message"></p><button class="primary-button" id="retry">Try WebGL2</button>`;document.querySelector('#failure-message')!.textContent=message;document.querySelector('#retry')!.addEventListener('click',()=>{const u=new URL(location.href);u.searchParams.set('renderer','webgl');location.href=u.href;});}
  setView(view:number){const names=['The waterfront','Downtown, slowed down','Paloma Island'],sub=['Ocean air. City energy.','A different kind of rush hour.','Find your own patch of paradise.'];document.querySelector('#location-title')!.textContent=names[view];document.querySelector('#location-subtitle')!.textContent=sub[view];document.querySelector('.location-number')!.textContent=`0${view+1} / 03`;document.querySelectorAll<HTMLElement>('[data-view]').forEach(el=>el.classList.toggle('active',Number(el.dataset.view)===view));this.actions.view(view);}
  playing(on:boolean){this.menu.hidden=on;this.hud.hidden=!on;}
  open(tab='graphics'){this.root.dispatchEvent(new CustomEvent('panel-opened'));this.renderTab(tab);if(!this.dialog.open)this.dialog.showModal();}
  close(){this.dialog.close();this.root.dispatchEvent(new CustomEvent('panel-closed'));}
  notify(text:string){this.toast.textContent=text;this.toast.hidden=false;clearTimeout(this.toastTimer);this.toastTimer=window.setTimeout(()=>this.toast.hidden=true,4200);}
  renderTab(tab:string){
    document.querySelectorAll<HTMLElement>('[data-tab]').forEach(el=>el.classList.toggle('active',el.dataset.tab===tab));const body=document.querySelector('#panel-body')!;const s=this.settings;
    const select=(label:string,key:string,options:string[],value:string)=>`<label class="setting-row"><span>${label}</span><select data-setting="${key}" aria-label="${label}">${options.map(v=>`<option ${v===value?'selected':''}>${v}</option>`).join('')}</select></label>`;
    const range=(label:string,key:string,min:number,max:number,step:number,value:number)=>`<label class="setting-row range-row"><span>${label}<output id="value-${key}">${value}</output></span><input aria-label="${label}" data-setting="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"/></label>`;
    const check=(label:string,key:string,value:boolean)=>`<label class="setting-row"><span>${label}</span><input data-setting="${key}" aria-label="${label}" type="checkbox" ${value?'checked':''}/></label>`;
    if(tab==='graphics')body.innerHTML=`<p class="panel-intro">Find your balance of beautiful and smooth. Changes apply immediately.</p>${select('Graphics preset','quality',['Low','Medium','High','Ultra'],s.quality)}${select('World culling / streaming','culling',['OFF','LOW','MEDIUM','HIGH','AUTO'],s.culling)}<p class="setting-help">LOW retains a wider area. HIGH unloads distant blocks more aggressively. OFF keeps every block resident. Render distance separately controls visibility and detail; collision and the sky remain active.</p>${range('Render distance (m)','distance',140,700,20,s.distance)}<div class="quality-readout" id="quality-readout"></div>${check('Performance overlay','debug',s.debug)}${check('Geometry wireframe','wireframe',s.wireframe)}<p class="setting-help">WebGPU preferred · automatic WebGL2 fallback. MSAA is enabled. Shared 256px environment texture; no costly screen-space AO or ray tracing.</p>`;
    if(tab==='world')body.innerHTML=`<p class="panel-intro">Chase the golden hour. Or let the day find its own rhythm.</p>${range('Time of day','time',0,23.9,.1,Math.round(s.time*10)/10)}<div class="time-presets">${[['Sunrise','6.5'],['Day','12'],['Golden','17'],['Sunset','18'],['Night','22']].map(([l,t])=>`<button data-time="${t}">${l}</button>`).join('')}</div>${check('24-hour day / night cycle','cycle',s.cycle)}${select('Weather','weather',['Clear','Cloudy','Rain'],s.weather)}<p class="setting-help">One full day takes about 22 minutes. Sun and Moon are independent of all world culling settings. Roads gradually become wet in rain and dry after it clears.</p><button id="respawn" class="secondary-button">Return to the waterfront</button><button id="reset-trip" class="text-button">Reset exploration progress</button>`;
    if(tab==='controls')body.innerHTML=`<p class="panel-intro">No rush. No wrong turns. Just somewhere new.</p><div class="control-list"><p><kbd>W A S D</kbd><span>Walk · drive · steer your boat</span></p><p><kbd>SHIFT</kbd><span>Sprint on foot</span></p><p><kbd>SPACE</kbd><span>Jump · vehicle brake</span></p><p><kbd>E</kbd><span>Enter / exit a nearby car or boat</span></p><p><kbd>DRAG</kbd><span>Look around · scroll to zoom</span></p><p><kbd>ESC</kbd><span>Pause and settings</span></p></div><p class="setting-help">On touchscreens, use the left joystick to move and drag the world to look. Hold RUN to sprint. Find the coral car on the road and the boat beside the marina. Bring boats near a dock or beach before exiting.</p>${range('Camera sensitivity','sensitivity',.3,2,.1,s.sensitivity)}${range('Field of view','fov',45,85,1,s.fov)}<p class="setting-help">An original procedural world. No accounts, paid APIs or online backend. Your graphics preferences stay on this device; exploration resets when the app closes.</p>`;
    body.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-setting]').forEach(el=>el.addEventListener('input',()=>{const key=el.dataset.setting as keyof Settings;const value=el instanceof HTMLInputElement?(el.type==='checkbox'?el.checked:Number(el.value)):el.value;this.actions.settings({[key]:value});const out=document.getElementById(`value-${key}`);if(out)out.textContent=String(value);this.readout();}));
    body.querySelectorAll<HTMLElement>('[data-time]').forEach(el=>el.onclick=()=>{this.actions.settings({time:Number(el.dataset.time),cycle:false});this.renderTab('world');});
    body.querySelector('#respawn')?.addEventListener('click',()=>{this.actions.respawn();this.close();});body.querySelector('#reset-trip')?.addEventListener('click',()=>{this.actions.reset();this.notify('A fresh start. Your coast is waiting.');});this.readout();
  }
  readout(){const el=document.querySelector('#quality-readout'),p=presets[this.settings.quality];if(el)el.textContent=`${p.dpr}× resolution cap · ${p.shadow||'No'} shadow map · ${p.population} traffic cars · ${p.rain} rain particles`;}
  time(){const t=clock(this.settings.time);document.querySelector('#menu-time')!.textContent=t;document.querySelector('#game-time')!.textContent=t;document.querySelector('#menu-weather')!.textContent=`${this.settings.weather==='Rain'?'24°':'27°'}  ${this.settings.weather==='Clear'?'Clear skies':this.settings.weather} · ${phase(this.settings.time)}`;}
}
